name: Documentation Check

on:
  push:
    branches: [gh-pages]

jobs:
  check-documentation-links:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.cache/pip
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Run Link Test 🔗
        run: |
          git clone https://github.com/janothan/invalid-url-check.git
          git clone -b gh-pages https://github.com/dwslab/melt.git
          cd ./invalid-url-check
          mvn clean install
          cd ./target
          java -jar invalid-url-check-1.0-SNAPSHOT.jar ../../melt