name: Java CI

on: [push]

jobs:
  build-multi-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latests]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.cache/pip
        key: ${{ matrix.os }}-m2-${{ hashFiles('**/pom.xml') }}-1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install python dependencies
      run: pip install -r ./matching-ml/src/main/resources/requirements.txt
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn clean install