name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Cache OAEI
      uses: actions/cache@v1
      with:
        path: ~/oaei_track_cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/TrackRepository.java') }}
        restore-keys: ${{ runner.os }}-oaei
    - name: Setup Python
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install -r ./matching-ml/oaei-resources/requirements.txt
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Coveralls
      run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS }}